[dosbox]
machine=cga

[autoexec]
mount C D:/
C:
cd BORLANDC/BIN
del err.txt
bcc KEYBOARD.C utils.c sprite.c game.c main.c >> err.txt
tlink c0s.obj utils.obj KEYBOARD.obj sprite.obj game.obj main.obj, main.exe, , cs.lib
main